backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: projects_zh_tw
    label: Projects (zh-TW)
    folder: content/projects/zh-TW
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: frontmatter
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Summary, name: summary, widget: text, required: false }
      - { label: Body, name: body, widget: markdown }

  - name: projects_en
    label: Projects (en)
    folder: content/projects/en
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: frontmatter
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Summary, name: summary, widget: text, required: false }
      - { label: Body, name: body, widget: markdown }

  - name: projects_ja
    label: Projects (ja)
    folder: content/projects/ja
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: frontmatter
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Summary, name: summary, widget: text, required: false }
      - { label: Body, name: body, widget: markdown }
